### ISSUE TITLE
Question about playing tones

### ISSUE THREAD

**Issue by hoilett** [kristerseiya/GuWatch#1]
Hi Alfred,
This is what an 8-bit tone sounds like https://youtu.be/-kkxs_fekWM
Is that what you wanted or did you want full MP3 quality?

**Comment by kristerseiya** [comment]
8-bit is not good enough for me. I would like to have more. 
MP3 quality is desired but it can be a lesser quality.

> Hi Alfred,
> This is what an 8-bit tone sounds like https://youtu.be/-kkxs_fekWM
> Is that what you wanted or did you want full MP3 quality?

**Comment by hoilett** [comment]
Sounds good.
Thanks.
